name: CI Build
'on':
  push:

jobs:  
  create-and-publish-image:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:     
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: '${{github.actor}}'
          password: '${{secrets.GITHUB_TOKEN}}'
      - name: Build Image
        run: docker build -t ghcr.io/team-one-pos-tech/snackhubweb -f ./snackhub/src/Dockerfile .
      - name: Push Image
        run: docker push ghcr.io/team-one-pos-tech/snackhubweb